name: Build Macos
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [macos-latest]
    timeout-minutes: 360
 
    steps:
      - uses: actions/checkout@v4
      - run: mkdir runner
      - name: Setup App
        working-directory: ./runner
        run: |
              bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
              brew install --cask docker
              curl -L https://github.com/docker/machine/releases/download/v0.16.1/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine
              chmod +x /usr/local/bin/docker-machine
              brew install --cask virtualbox
              docker-machine create --driver virtualbox default
              docker-machine create --driver virtualbox --virtualbox-no-vtx-check default
              eval "$(docker-machine env default)"
              docker version
              docker info 
              docker ps 
              docker run hello-world
        shell: bash
